// artemisEvents.js

export const missionEvents = [
  // ==========================================
  // --- PRE-LANZAMIENTO (T-MINUS) ---
  // ==========================================
  {
    title: "❄️ Carga de Propulsantes",
    titleEn: "❄️ Propellant Load",
    desc: "Inicia la carga de oxígeno líquido (LOX) e hidrógeno líquido (LH2) criogénicos en la etapa central del cohete SLS.",
    descEn:
      "Cryogenic liquid oxygen (LOX) and liquid hydrogen (LH2) loading begins in the SLS core stage.",
    phase: "Prelaunch",
    attitude: "Pad 39B",
    isRoutine: false,
    days: 0,
    hours: -8,
    minutes: 0,
  },
  {
    title: "🚶‍♂️ Walkout de Tripulación",
    titleEn: "🚶‍♂️ Crew Walkout",
    desc: "Los astronautas salen del edificio O&C y suben a los vehículos de transporte Astrovan hacia la plataforma.",
    descEn:
      "Astronauts exit the O&C building and board the Astrovan transport vehicles to the pad.",
    phase: "Prelaunch",
    attitude: "Pad 39B",
    isRoutine: true,
    days: 0,
    hours: -4,
    minutes: -30,
  },
  {
    title: "🧑‍🚀 Ingreso a la Cápsula",
    titleEn: "🧑‍🚀 Capsule Ingress",
    desc: 'La tripulación llega a la "White Room" en la torre de lanzamiento y comienza a ingresar a Orion.',
    descEn:
      'The crew arrives at the "White Room" on the launch tower and begins boarding Orion.',
    phase: "Prelaunch",
    attitude: "Pad 39B",
    isRoutine: false,
    days: 0,
    hours: -3,
    minutes: -15,
  },
  {
    title: "🚪 Cierre de Escotilla",
    titleEn: "🚪 Hatch Closure",
    desc: "Se cierra y sella la escotilla lateral de Orion. Pruebas de estanqueidad en curso.",
    descEn:
      "Orion's side hatch is closed and sealed. Leak checks are underway.",
    phase: "Prelaunch",
    attitude: "Pad 39B",
    isRoutine: false,
    days: 0,
    hours: -2,
    minutes: -10,
  },
  {
    title: "⏱️ Cuenta Regresiva Terminal",
    titleEn: "⏱️ Terminal Countdown",
    desc: 'El Director de Lanzamiento da el "GO" final. Inicia la cuenta regresiva automatizada.',
    descEn:
      'The Launch Director gives the final "GO". Automated countdown initiates.',
    phase: "Prelaunch",
    attitude: "Pad 39B",
    isRoutine: false,
    days: 0,
    hours: 0,
    minutes: -10,
  },
  {
    title: "💻 Traspaso a Ordenadores (Hand-off)",
    titleEn: "💻 Auto Sequence Hand-off",
    desc: "Los sistemas de tierra ceden el control a los ordenadores de vuelo del SLS. Inicia secuencia de ignición.",
    descEn:
      "Ground systems hand off control to SLS flight computers. Ignition sequence begins.",
    phase: "Prelaunch",
    attitude: "Pad 39B",
    isRoutine: false,
    days: 0,
    hours: 0,
    minutes: -1,
  },

  // ==========================================
  // --- DÍA 1 (FD01): ÓRBITA TERRESTRE BAJA (LEO) ---
  // ==========================================
  {
    title: "🚀 Despegue (Ascent)",
    titleEn: "🚀 Liftoff (Ascent)",
    desc: "Los motores RS-25 y propulsores sólidos cobran vida. Inicio oficial del reloj MET[cite: 31, 505].",
    descEn:
      "RS-25 engines and solid boosters come to life. Official start of the MET clock[cite: 31, 505].",
    phase: "Ascent",
    attitude: "Ascent",
    isRoutine: false,
    days: 0,
    hours: 0,
    minutes: 0,
  },
  {
    title: "🌬️ Despresurización (DFTO 3, 2)",
    titleEn: "🌬️ Cabin Depress (DFTO 3, 2)",
    desc: "Prueba de estanqueidad de los trajes espaciales. Se reduce la presión de la cabina intencionalmente[cite: 76].",
    descEn:
      "Spacesuit seal test. Cabin pressure is intentionally reduced[cite: 76].",
    phase: "Ascent",
    attitude: "Ascent",
    isRoutine: false,
    days: 0,
    hours: 0,
    minutes: 30,
  },
  {
    title: "📷 Prueba Cámara de Acoplamiento (00:40)",
    titleEn: "📷 Dock Cam Misalign (00:40)",
    desc: "Primera verificación de alineación de la cámara de acoplamiento post-lanzamiento[cite: 74].",
    descEn:
      "First post-launch alignment check of the docking camera[cite: 74].",
    phase: "LEO",
    attitude: "MNVRS",
    isRoutine: false,
    days: 0,
    hours: 0,
    minutes: 40,
  },
  {
    title: "🔥 Elevación de Perigeo (ICPS PRM)",
    titleEn: "🔥 Perigee Raise Maneuver (ICPS PRM)",
    desc: "La etapa superior enciende motores para estabilizar la órbita inicial a los 50 minutos del vuelo[cite: 69].",
    descEn:
      "The upper stage fires engines to stabilize initial orbit 50 minutes into flight[cite: 69].",
    phase: "LEO",
    attitude: "MNVRS",
    isRoutine: false,
    days: 0,
    hours: 0,
    minutes: 50,
  },
  {
    title: "🔥 Elevación de Apogeo (ARB TIG)",
    titleEn: "🔥 Apogee Raise Burn (ARB TIG)",
    desc: "Encendido para alargar la órbita de forma elíptica para ganar altura[cite: 71].",
    descEn:
      "Burn to elongate the orbit elliptically to gain altitude[cite: 71].",
    phase: "LEO",
    attitude: "ARB",
    isRoutine: false,
    days: 0,
    hours: 1,
    minutes: 48,
  },
  {
    title: "🧑‍🚀 Retirada de Trajes (Doff OCSS)",
    titleEn: "🧑‍🚀 Doff Survival Suits (OCSS)",
    desc: "Los astronautas se quitan los pesados trajes anaranjados de supervivencia Orion Crew Survival System[cite: 37].",
    descEn:
      "Astronauts take off the heavy orange Orion Crew Survival System suits[cite: 37].",
    phase: "LEO",
    attitude: "B-XSI",
    isRoutine: true,
    days: 0,
    hours: 2,
    minutes: 30,
  },
  {
    title: "🔗 Separación Orion/ICPS",
    titleEn: "🔗 Orion/ICPS Spring Sep",
    desc: "La nave Orion se desconecta físicamente de la etapa superior mediante resortes a las 3 horas y 24 minutos[cite: 70].",
    descEn:
      "Orion spacecraft physically disconnects from the upper stage via springs at 3 hours 24 minutes[cite: 70].",
    phase: "LEO",
    attitude: "B-XSI",
    isRoutine: false,
    days: 0,
    hours: 3,
    minutes: 24,
  },
  {
    title: "🛰️ Prox Ops Demo (Orion USS)",
    titleEn: "🛰️ Prox Ops Demo (Orion USS)",
    desc: "Los astronautas prueban el control manual volando en proximidad a la etapa descartada[cite: 38, 72].",
    descEn:
      "Astronauts test manual controls flying in proximity to the discarded stage[cite: 38, 72].",
    phase: "LEO",
    attitude: "Prox Ops Demo",
    isRoutine: false,
    days: 0,
    hours: 4,
    minutes: 52,
  },
  {
    title: "📷 Calibración de Cámara (Dock Cam Bearing)",
    titleEn: "📷 Dock Cam Bearing",
    desc: "Alineación de orientación (bearing) de la cámara óptica durante maniobras de proximidad[cite: 78].",
    descEn:
      "Optical camera bearing alignment during proximity maneuvers[cite: 78].",
    phase: "LEO",
    attitude: "Prox Ops Demo",
    isRoutine: false,
    days: 0,
    hours: 4,
    minutes: 57,
  },
  {
    title: "🗑️ Encendido de Descarte (ICPS Disposal)",
    titleEn: "🗑️ ICPS Disposal Burn",
    desc: "La etapa ICPS enciende su motor para alejarse hacia una órbita cementerio segura a las 5 horas[cite: 77].",
    descEn:
      "The ICPS stage fires its engine to move to a safe graveyard orbit at the 5-hour mark[cite: 77].",
    phase: "LEO",
    attitude: "Bias -XSI",
    isRoutine: false,
    days: 0,
    hours: 5,
    minutes: 2,
  },
  {
    title: "☀️ Despliegue de Paneles (SPL)",
    titleEn: "☀️ Solar Panel Deploy (SPL)",
    desc: 'El Módulo de Servicio Europeo despliega sus cuatro paneles solares en forma de "X"[cite: 73].',
    descEn:
      'The European Service Module deploys its four "X" shaped solar arrays[cite: 73].',
    phase: "LEO",
    attitude: "Bias -XSI",
    isRoutine: false,
    days: 0,
    hours: 5,
    minutes: 27,
  },
  {
    title: "🍲 Configuración de Cabina",
    titleEn: "🍲 Cabin Config",
    desc: "Organización de los suministros dentro de la cápsula[cite: 39].",
    descEn: "Organization of supplies inside the capsule[cite: 39].",
    phase: "LEO",
    attitude: "Bias -XSI",
    isRoutine: true,
    days: 0,
    hours: 6,
    minutes: 0,
  },
  {
    title: "🎙️ Chequeos PAD / PMC",
    titleEn: "🎙️ PAD / PMC Checks",
    desc: "Conferencia médica privada y revisión de Datos de Asesoramiento Preliminar[cite: 43].",
    descEn:
      "Private medical conference and Preliminary Advisory Data review[cite: 43].",
    phase: "LEO",
    attitude: "Bias -XSI",
    isRoutine: true,
    days: 0,
    hours: 7,
    minutes: 0,
  },
  {
    title: "💤 Primer Ciclo de Sueño (4 hrs)",
    titleEn: "💤 First Sleep Cycle (4 hrs)",
    desc: "Breve descanso de la tripulación tras la jornada de lanzamiento[cite: 44].",
    descEn: "Brief crew rest after the launch day[cite: 44].",
    phase: "High Earth Orbit",
    attitude: "Bias -XSI",
    isRoutine: true,
    days: 0,
    hours: 8,
    minutes: 30,
  },
  {
    title: "📡 Activación OpComm",
    titleEn: "📡 OpComm Activation",
    desc: "Activación inicial del sistema de comunicaciones ópticas láser[cite: 74].",
    descEn:
      "Initial activation of the laser optical communications system[cite: 74].",
    phase: "High Earth Orbit",
    attitude: "Bias -XSI",
    isRoutine: false,
    days: 0,
    hours: 10,
    minutes: 6,
  },
  {
    title: "🔥 Orion PRB",
    titleEn: "🔥 Orion Perigee Raise Burn (PRB)",
    desc: "Orion enciende su motor principal para ajustar la órbita final antes de saltar a la Luna[cite: 75].",
    descEn:
      "Orion fires its main engine to adjust final orbit before jumping to the Moon[cite: 75].",
    phase: "High Earth Orbit",
    attitude: "PRB OpNa",
    isRoutine: false,
    days: 0,
    hours: 13,
    minutes: 45,
  },
  {
    title: "💤 Segundo Sueño (4.5 hrs)",
    titleEn: "💤 Second Sleep (4.5 hrs)",
    desc: "Ciclo de descanso principal para prepararse para la inyección lunar[cite: 63].",
    descEn: "Main sleep cycle to prepare for lunar injection[cite: 63].",
    phase: "High Earth Orbit",
    attitude: "Bias -XSI",
    isRoutine: true,
    days: 0,
    hours: 14,
    minutes: 30,
  },

  // ==========================================
  // --- DÍA 2 (FD02): HACIA LA LUNA ---
  // ==========================================
  {
    title: "💻 Chequeos HEO y Ejercicio",
    titleEn: "💻 HEO Systems Checkout & Exercise",
    desc: "Pruebas de los sistemas HEO y prueba de los equipos de ejercicio resistivo[cite: 87].",
    descEn:
      "HEO systems testing and resistive exercise equipment test[cite: 87].",
    phase: "High Earth Orbit",
    attitude: "Bias -XSI",
    isRoutine: false,
    days: 0,
    hours: 22,
    minutes: 0,
  },
  {
    title: "🚀 Inyección Trans-Lunar (Orion TLI)",
    titleEn: "🚀 Trans-Lunar Injection (Orion TLI)",
    desc: "Encendido principal. La nave abandona la Tierra rumbo a la Luna[cite: 125].",
    descEn: "Main burn. The ship leaves Earth heading for the Moon[cite: 125].",
    phase: "Trans-Lunar",
    attitude: "TLI",
    isRoutine: false,
    days: 1,
    hours: 1,
    minutes: 37,
  },
  {
    title: "🍲 Comida Post-TLI",
    titleEn: "🍲 Post-TLI Meal",
    desc: "Comida tras la exitosa maniobra de inyección lunar[cite: 107].",
    descEn: "Meal after successful lunar injection maneuver[cite: 107].",
    phase: "Trans-Lunar",
    attitude: "Bias -XSI",
    isRoutine: true,
    days: 1,
    hours: 2,
    minutes: 30,
  },
  {
    title: "🛠️ Desmontaje de Soportes",
    titleEn: "🛠️ Asc Bracket Uninstall",
    desc: "Desmontaje de cámaras y soportes usados durante el ascenso para liberar espacio[cite: 128].",
    descEn:
      "Uninstalling cameras and brackets used during ascent to free up space[cite: 128].",
    phase: "Trans-Lunar",
    attitude: "Bias -XSI",
    isRoutine: false,
    days: 1,
    hours: 3,
    minutes: 0,
  },
  {
    title: "🎙️ Evento PAO (FD02)",
    titleEn: "🎙️ PAO Event (FD02)",
    desc: "Oficina de Asuntos Públicos: enlace en vivo desde el espacio profundo[cite: 109].",
    descEn: "Public Affairs Office: live link from deep space[cite: 109].",
    phase: "Trans-Lunar",
    attitude: "Bias -XSI",
    isRoutine: true,
    days: 1,
    hours: 4,
    minutes: 0,
  },
  {
    title: "👀 Inspección de Ventanas",
    titleEn: "👀 Window Inspect",
    desc: "Inspección visual detallada de las ventanas de la cápsula en busca de microimpactos[cite: 110].",
    descEn:
      "Detailed visual inspection of capsule windows for micro-impacts[cite: 110].",
    phase: "Trans-Lunar",
    attitude: "Bias -XSI",
    isRoutine: false,
    days: 1,
    hours: 5,
    minutes: 30,
  },
  {
    title: "🔍 Inspección Térmica (CM/SM Survey)",
    titleEn: "🔍 Thermal Inspection (CM/SM Survey)",
    desc: "Uso de cámaras en los paneles para escanear el escudo térmico buscando daños[cite: 127].",
    descEn:
      "Use of solar array cameras to scan the heat shield for damage[cite: 127].",
    phase: "Trans-Lunar",
    attitude: "Survey",
    isRoutine: false,
    days: 1,
    hours: 12,
    minutes: 0,
  },
  {
    title: "💤 Sueño en Espacio Profundo (8.5 hrs)",
    titleEn: "💤 Deep Space Sleep (8.5 hrs)",
    desc: "Ciclo de descanso estándar de 8.5 horas establecido para el resto del tránsito[cite: 114].",
    descEn:
      "Standard 8.5 hour rest cycle established for the remainder of transit[cite: 114].",
    phase: "Trans-Lunar",
    attitude: "Bias -XSI",
    isRoutine: true,
    days: 1,
    hours: 13,
    minutes: 0,
  },

  // ==========================================
  // --- DÍA 3 (FD03): OPERACIONES EN TRÁNSITO ---
  // ==========================================
  {
    title: "🛠️ OTC-1",
    titleEn: "🛠️ OTC-1",
    desc: "Primera corrección de trayectoria de ida (Outbound Trajectory Correction)[cite: 211].",
    descEn: "First Outbound Trajectory Correction burn[cite: 211].",
    phase: "Trans-Lunar",
    attitude: "OTC1",
    isRoutine: false,
    days: 2,
    hours: 0,
    minutes: 7,
  },
  {
    title: "⚙️ Prueba de Volante de Inercia",
    titleEn: "⚙️ Flywheel Day in the Life",
    desc: "Comprobación de los sistemas inerciales de la nave en condiciones reales de vuelo[cite: 184, 187].",
    descEn:
      "Check of the spacecraft's inertial systems in real flight conditions[cite: 184, 187].",
    phase: "Trans-Lunar",
    attitude: "Bias -XSI",
    isRoutine: false,
    days: 2,
    hours: 2,
    minutes: 0,
  },
  {
    title: "💻 Prueba de Comando HERA",
    titleEn: "💻 HERA Command DFTO",
    desc: "Prueba de la Interfaz del Sistema de Exposición a la Radiación[cite: 131].",
    descEn: "Test of the Radiation Exposure System Interface[cite: 131].",
    phase: "Trans-Lunar",
    attitude: "Bias -XSI",
    isRoutine: false,
    days: 2,
    hours: 4,
    minutes: 0,
  },
  {
    title: "🩺 Demo de RCP y Kit Médico",
    titleEn: "🩺 CPR Demo & Med Kit",
    desc: "Los astronautas realizan una demostración de Resucitación Cardiopulmonar (CPR) en microgravedad[cite: 193, 194, 237].",
    descEn:
      "Astronauts perform a Cardiopulmonary Resuscitation (CPR) demo in microgravity[cite: 193, 194, 237].",
    phase: "Trans-Lunar",
    attitude: "Bias -XSI",
    isRoutine: true,
    days: 2,
    hours: 6,
    minutes: 0,
  },
  {
    title: "📡 Enlace DSN de Emergencia",
    titleEn: "📡 DSN Emergency Comms",
    desc: "Prueba de enlace de emergencia con la Red del Espacio Profundo (DSN)[cite: 195, 197].",
    descEn:
      "Emergency link test with the Deep Space Network (DSN)[cite: 195, 197].",
    phase: "Trans-Lunar",
    attitude: "FTO",
    isRoutine: false,
    days: 2,
    hours: 8,
    minutes: 0,
  },
  {
    title: "🎙️ Evento PAO (Agencia Canadiense)",
    titleEn: "🎙️ CSA PAO Event",
    desc: "Enlace exclusivo con la Agencia Espacial Canadiense (CSA) en honor al astronauta canadiense a bordo[cite: 201].",
    descEn:
      "Exclusive link with the Canadian Space Agency (CSA) honoring the Canadian astronaut on board[cite: 201].",
    phase: "Trans-Lunar",
    attitude: "Bias -XSI",
    isRoutine: true,
    days: 2,
    hours: 10,
    minutes: 0,
  },
  {
    title: "💤 Ciclo de Sueño (FD03)",
    titleEn: "💤 Sleep Cycle (FD03)",
    desc: "Descanso de 8.5 horas[cite: 269].",
    descEn: "8.5 hours rest[cite: 269].",
    phase: "Trans-Lunar",
    attitude: "Bias -XSI",
    isRoutine: true,
    days: 2,
    hours: 13,
    minutes: 0,
  },

  // ==========================================
  // --- DÍA 4 (FD04): AJUSTES FINOS ---
  // ==========================================
  {
    title: "🛠️ OTC-2",
    titleEn: "🛠️ OTC-2",
    desc: "Segunda corrección de trayectoria para afinar el ángulo lunar[cite: 285].",
    descEn:
      "Second trajectory correction to refine the lunar angle[cite: 285].",
    phase: "Trans-Lunar",
    attitude: "OTC2",
    isRoutine: false,
    days: 3,
    hours: 0,
    minutes: 12,
  },
  {
    title: "🎧 Inicio DFTO Acústico (24h)",
    titleEn: "🎧 Start 24h Acoustic DFTO",
    desc: "Comienza una prueba de medición continua de ruido ambiental en la cabina durante 24 horas[cite: 286].",
    descEn:
      "Starts a 24-hour continuous ambient noise measurement test in the cabin[cite: 286].",
    phase: "Trans-Lunar",
    attitude: "Bias -XSI",
    isRoutine: false,
    days: 3,
    hours: 2,
    minutes: 0,
  },
  {
    title: "📏 Medición de Cámara Óptica",
    titleEn: "📏 Doc Cam Measure",
    desc: "Toma manual de medidas e calibración óptica de los sensores de navegación[cite: 260, 262].",
    descEn:
      "Manual measurements and optical calibration of navigation sensors[cite: 260, 262].",
    phase: "Trans-Lunar",
    attitude: "DFTO",
    isRoutine: false,
    days: 3,
    hours: 7,
    minutes: 0,
  },
  {
    title: "📷 Prueba Misalign Cámara",
    titleEn: "📷 Dock Cam Misalign Test",
    desc: "Prueba forzando una desalineación virtual de la cámara óptica a las 15h 30m del MET[cite: 292].",
    descEn:
      "Test forcing a virtual misalignment of the optical camera at MET 15h 30m[cite: 292].",
    phase: "Trans-Lunar",
    attitude: "Bias -XSI",
    isRoutine: false,
    days: 3,
    hours: 15,
    minutes: 30,
  },
  {
    title: "💤 Ciclo de Sueño (FD04)",
    titleEn: "💤 Sleep Cycle (FD04)",
    desc: "Descanso de la tripulación en trayectoria hacia la Luna[cite: 276].",
    descEn: "Crew rest en route to the Moon[cite: 276].",
    phase: "Trans-Lunar",
    attitude: "Bias -XSI",
    isRoutine: true,
    days: 3,
    hours: 16,
    minutes: 0,
  },

  // ==========================================
  // --- DÍA 5 (FD05): EL ENCUENTRO LUNAR ---
  // ==========================================
  {
    title: "🎧 Fin DFTO Acústico",
    titleEn: "🎧 End 24h Acoustic DFTO",
    desc: "Finaliza la grabación ambiental de 24 horas. Se envían datos a la Tierra[cite: 326].",
    descEn:
      "24-hour ambient recording ends. Data is downlinked to Earth[cite: 326].",
    phase: "Trans-Lunar",
    attitude: "Bias -XSI",
    isRoutine: false,
    days: 4,
    hours: 2,
    minutes: 0,
  },
  {
    title: "🛠️ OTC-3",
    titleEn: "🛠️ OTC-3",
    desc: "Tercera y última corrección propulsada antes de la influencia gravitacional lunar[cite: 327].",
    descEn:
      "Third and final powered correction before entering lunar gravitational influence[cite: 327].",
    phase: "Trans-Lunar",
    attitude: "Bias -XSI",
    isRoutine: false,
    days: 4,
    hours: 5,
    minutes: 23,
  },
  {
    title: "🌑 Entrada Esfera Lunar (SOI Entry)",
    titleEn: "🌑 Lunar SOI Entry",
    desc: "Orion cruza la frontera donde la gravedad de la Luna supera a la de la Tierra[cite: 366].",
    descEn:
      "Orion crosses the boundary where the Moon's gravity exceeds Earth's[cite: 366].",
    phase: "Trans-Lunar",
    attitude: "Bias -XSI",
    isRoutine: false,
    days: 4,
    hours: 6,
    minutes: 59,
  },
  {
    title: "🌬️ Venteo a 10.2 psi",
    titleEn: "🌬️ Vent to 10.2 psi",
    desc: "Se iguala la presión de la cabina a niveles reducidos de prueba[cite: 354].",
    descEn: "Cabin pressure is equalized to reduced test levels[cite: 354].",
    phase: "Trans-Lunar",
    attitude: "Bias -XSI",
    isRoutine: false,
    days: 4,
    hours: 8,
    minutes: 0,
  },
  {
    title: "💤 Ciclo de Sueño (FD05)",
    titleEn: "💤 Sleep Cycle (FD05)",
    desc: "El último descanso antes del dramático encuentro lunar[cite: 367].",
    descEn: "The final rest before the dramatic lunar encounter[cite: 367].",
    phase: "Trans-Lunar",
    attitude: "Bias -XSI",
    isRoutine: true,
    days: 4,
    hours: 13,
    minutes: 0,
  },
  {
    title: "🏆 Récord Apollo 13",
    titleEn: "🏆 Apollo 13 Record Broken",
    desc: "La tripulación rompe el récord de mayor distancia de la Tierra alcanzada por humanos[cite: 347].",
    descEn:
      "The crew breaks the record for the furthest distance from Earth reached by humans[cite: 347].",
    phase: "Trans-Lunar",
    attitude: "Bias -XSI",
    isRoutine: false,
    days: 4,
    hours: 21,
    minutes: 2,
  },
  {
    title: "🌕 Máximo Acercamiento Lunar",
    titleEn: "🌕 Lunar Close Approach",
    desc: "Orion vuela a ras de la cara oculta de la Luna. Se pierde temporalmente la señal[cite: 402].",
    descEn:
      "Orion flies close over the far side of the Moon. Signal is temporarily lost[cite: 402].",
    phase: "Trans-Earth",
    attitude: "Nav",
    isRoutine: false,
    days: 5,
    hours: 1,
    minutes: 23,
  },
  {
    title: "🌌 Máxima Distancia Terrestre",
    titleEn: "🌌 Max Earth Distance",
    desc: "El punto más alejado del planeta natal en toda la misión[cite: 402].",
    descEn:
      "The furthest point from the home planet in the entire mission[cite: 402].",
    phase: "Trans-Earth",
    attitude: "Nav",
    isRoutine: false,
    days: 5,
    hours: 1,
    minutes: 26,
  },
  {
    title: "📡 Prueba Modo SAT",
    titleEn: "📡 SAT Mode Test",
    desc: "Prueba técnica de las antenas tras reaparecer de la sombra lunar[cite: 366].",
    descEn:
      "Technical test of antennas after emerging from the lunar shadow[cite: 366].",
    phase: "Trans-Earth",
    attitude: "Bias -XSI",
    isRoutine: false,
    days: 5,
    hours: 7,
    minutes: 5,
  },
  {
    title: "🔍 Inspección Post-Lunar (CM/SM Survey)",
    titleEn: "🔍 Post-Lunar Survey",
    desc: "Revisión externa crítica del escudo térmico tras pasar por el entorno de polvo y radiación lunar[cite: 404].",
    descEn:
      "Critical external review of the heat shield after passing through lunar dust and radiation environment[cite: 404].",
    phase: "Trans-Earth",
    attitude: "Survey",
    isRoutine: false,
    days: 5,
    hours: 12,
    minutes: 45,
  },
  {
    title: "🌍 Salida Esfera Lunar (SOI Exit)",
    titleEn: "🌍 Lunar SOI Exit",
    desc: "Salida de la influencia lunar. Comienza el viaje de caída libre hacia la Tierra[cite: 443].",
    descEn:
      "Exit from lunar influence. The free-fall journey back to Earth begins[cite: 443].",
    phase: "Trans-Earth",
    attitude: "Bias -XSI",
    isRoutine: false,
    days: 5,
    hours: 19,
    minutes: 47,
  },
  {
    title: "🥵 Ejercicio Intensivo ECLSS",
    titleEn: "🥵 Min ECLSS Exercise",
    desc: "Ejercicio vigoroso de la tripulación para poner a prueba los sistemas depuradores ambientales de la nave[cite: 444].",
    descEn:
      "Vigorous crew exercise to stress test the spacecraft's environmental scrubber systems[cite: 444].",
    phase: "Trans-Earth",
    attitude: "Bias -XSI",
    isRoutine: true,
    days: 5,
    hours: 21,
    minutes: 0,
  },
  {
    title: "💤 Sueño Profundo (9 hrs)",
    titleEn: "💤 Deep Sleep (9 hrs)",
    desc: "Ajuste de ciclo circadiano post-sobrevuelo. Turno extendido de sueño[cite: 438].",
    descEn:
      "Post-flyby circadian cycle adjustment. Extended sleep shift[cite: 438].",
    phase: "Trans-Earth",
    attitude: "Bias -XSI",
    isRoutine: true,
    days: 5,
    hours: 23,
    minutes: 0,
  },

  // ==========================================
  // --- DÍA 6 (FD06) - DÍA 8 (FD08): EL REGRESO ---
  // ==========================================
  {
    title: "🛠️ RTC-1",
    titleEn: "🛠️ RTC-1",
    desc: "Primera corrección de trayectoria de retorno para apuntar a la Tierra[cite: 445].",
    descEn:
      "First Return Trajectory Correction burn to aim for Earth[cite: 445].",
    phase: "Trans-Earth",
    attitude: "RTC1",
    isRoutine: false,
    days: 6,
    hours: 4,
    minutes: 23,
  },
  {
    title: "🎲 Tiempo Libre (Off Duty)",
    titleEn: "🎲 Off Duty Time",
    desc: "Primera franja de tiempo libre extendido asignada a la tripulación para relajarse y ver la Tierra acercarse[cite: 412].",
    descEn:
      "First extended free time block assigned to the crew to relax and watch Earth approach[cite: 412].",
    phase: "Trans-Earth",
    attitude: "Bias -XSI",
    isRoutine: true,
    days: 6,
    hours: 8,
    minutes: 0,
  },
  {
    title: "☢️ Refugio de Radiación Demo",
    titleEn: "☢️ Rad Shelter Demo",
    desc: "Prueba de construcción del refugio contra tormentas solares utilizando el almacenamiento interno[cite: 487].",
    descEn:
      "Test construction of the solar storm radiation shelter using internal storage[cite: 487].",
    phase: "Trans-Earth",
    attitude: "DFTO",
    isRoutine: false,
    days: 6,
    hours: 22,
    minutes: 0,
  },
  {
    title: "💤 Ciclo de Sueño (FD07)",
    titleEn: "💤 Sleep Cycle (FD07)",
    desc: "Últimos días de sueño en microgravedad[cite: 396].",
    descEn: "Final days of sleep in microgravity[cite: 396].",
    phase: "Trans-Earth",
    attitude: "Bias -XSI",
    isRoutine: true,
    days: 6,
    hours: 23,
    minutes: 0,
  },
  {
    title: "💧 Venteo de Orina al Vacío",
    titleEn: "💧 Urine Venting Test",
    desc: "Prueba del sistema de expulsión de líquidos hacia el espacio (Urine venting DFTO EM2-26)[cite: 501].",
    descEn:
      "Test of the liquid expulsion system into space (Urine venting DFTO EM2-26)[cite: 501].",
    phase: "Trans-Earth",
    attitude: "Bias -XSI",
    isRoutine: false,
    days: 7,
    hours: 4,
    minutes: 0,
  },
  {
    title: "💻 FCS Checkouts",
    titleEn: "💻 FCS Checkouts",
    desc: "Pruebas de los ordenadores del Sistema de Control de Vuelo (FCS) para asegurar la reentrada[cite: 524].",
    descEn:
      "Tests of the Flight Control System (FCS) computers to ensure safe reentry[cite: 524].",
    phase: "Trans-Earth",
    attitude: "Bias -XSI",
    isRoutine: false,
    days: 7,
    hours: 17,
    minutes: 30,
  },
  {
    title: "🌬️ Represurización a 14.7 psi",
    titleEn: "🌬️ Repress to 14.7 psi",
    desc: "Restauración de la presión de la cabina a niveles estándar del nivel del mar terrestre[cite: 504].",
    descEn:
      "Restoration of cabin pressure to standard Earth sea level[cite: 504].",
    phase: "Trans-Earth",
    attitude: "Bias -XSI",
    isRoutine: false,
    days: 7,
    hours: 20,
    minutes: 0,
  },
  {
    title: "🧑‍🚀 Colocación Trajes (OSG Don)",
    titleEn: "🧑‍🚀 Suit Up (OSG Don)",
    desc: "Los astronautas se ponen los trajes naranjas de supervivencia preparando el aterrizaje[cite: 517].",
    descEn:
      "Astronauts don orange survival suits preparing for landing[cite: 517].",
    phase: "Trans-Earth",
    attitude: "OSG Don DFTO",
    isRoutine: true,
    days: 7,
    hours: 21,
    minutes: 0,
  },
  {
    title: "💤 Último Sueño Orbital (8.5 hrs)",
    titleEn: "💤 Final Orbital Sleep (8.5 hrs)",
    desc: "Última noche en el espacio[cite: 547].",
    descEn: "Final night in space[cite: 547].",
    phase: "Trans-Earth",
    attitude: "Bias -XSI Mitigate X",
    isRoutine: true,
    days: 7,
    hours: 23,
    minutes: 0,
  },
  {
    title: "🛠️ RTC-2",
    titleEn: "🛠️ RTC-2",
    desc: "Ajuste fino milimétrico para acertar en el pasillo atmosférico[cite: 550].",
    descEn:
      "Millimetric fine-tuning to hit the atmospheric corridor[cite: 550].",
    phase: "Trans-Earth",
    attitude: "RTC",
    isRoutine: false,
    days: 8,
    hours: 4,
    minutes: 33,
  },
  {
    title: "🎒 Aseguramiento de Carga (Entry Stow)",
    titleEn: "🎒 Entry Stow",
    desc: "Guardado final de todos los objetos sueltos de la cabina. Evita proyectiles en la reentrada[cite: 544, 545].",
    descEn:
      "Final stowage of all loose cabin items. Prevents projectiles during reentry[cite: 544, 545].",
    phase: "Trans-Earth",
    attitude: "Entry Stow",
    isRoutine: true,
    days: 8,
    hours: 14,
    minutes: 0,
  },
  {
    title: "🛠️ RTC-3",
    titleEn: "🛠️ RTC-3",
    desc: "Último ajuste balístico directo hacia el Océano Pacífico antes de descartar el módulo[cite: 554].",
    descEn:
      "Final ballistic adjustment straight towards the Pacific Ocean before discarding the module[cite: 554].",
    phase: "Trans-Earth",
    attitude: "RTC3",
    isRoutine: false,
    days: 8,
    hours: 20,
    minutes: 33,
  },

  // ==========================================
  // --- DÍA 9 (FD09/10): REENTRADA Y AMERIZAJE ---
  // ==========================================
  {
    title: "🔗 Separación de Módulos (CM/SM Sep)",
    titleEn: "🔗 Module Separation (CM/SM Sep)",
    desc: "El Módulo de Servicio Europeo se descarta y se desintegra inofensivamente en la atmósfera[cite: 555].",
    descEn:
      "The European Service Module is discarded and burns up harmlessly in the atmosphere[cite: 555].",
    phase: "EDL",
    attitude: "Entry C/L",
    isRoutine: false,
    days: 9,
    hours: 1,
    minutes: 13,
  },
  {
    title: "🔥 Interfaz de Entrada (Reentrada)",
    titleEn: "🔥 Entry Interface",
    desc: "La cápsula golpea la atmósfera a Mach 32. El escudo térmico soporta 2,800°C. Comienza el apagón de radio[cite: 556].",
    descEn:
      "Capsule hits the atmosphere at Mach 32. Heat shield endures 2,800°C. Radio blackout begins[cite: 556].",
    phase: "EDL",
    attitude: "Entry C/L",
    isRoutine: false,
    days: 9,
    hours: 1,
    minutes: 33,
  },
  {
    title: "🌊 Amerizaje (Splashdown)",
    titleEn: "🌊 Splashdown",
    desc: "Amerizaje suave en las aguas del Océano Pacífico gracias a los tres paracaídas principales. ¡Misión cumplida! [cite: 557]",
    descEn:
      "Soft splashdown in the Pacific Ocean thanks to the three main parachutes. Mission accomplished! [cite: 557]",
    phase: "Recovery",
    attitude: "Recovery Ops",
    isRoutine: false,
    days: 9,
    hours: 1,
    minutes: 46,
  },
];
