// artemisEvents.js

export const missionEvents = [
  // ==========================================
  // --- PRE-LANZAMIENTO (T-MINUS) ---
  // ==========================================
  {
    title: "❄️ Carga de Propulsantes",
    titleEn: "❄️ Propellant Load",
    desc: "Inicia la carga de oxígeno líquido (LOX) e hidrógeno líquido (LH2) criogénicos en la etapa central del cohete SLS.",
    descEn:
      "Cryogenic liquid oxygen (LOX) and liquid hydrogen (LH2) loading begins in the SLS core stage.",
    phase: "Prelaunch",
    attitude: "Pad 39B",
    isRoutine: false,
    days: 0,
    hours: -8,
    minutes: 0,
  },
  {
    title: "🚶‍♂️ Walkout de Tripulación",
    titleEn: "🚶‍♂️ Crew Walkout",
    desc: "Los astronautas salen del edificio O&C y suben a los vehículos de transporte Astrovan hacia la plataforma.",
    descEn:
      "Astronauts exit the O&C building and board the Astrovan transport vehicles to the pad.",
    phase: "Prelaunch",
    attitude: "Pad 39B",
    isRoutine: true,
    days: 0,
    hours: -4,
    minutes: -30,
  },
  {
    title: "🧑‍🚀 Ingreso a la Cápsula",
    titleEn: "🧑‍🚀 Capsule Ingress",
    desc: 'La tripulación llega a la "White Room" en la torre de lanzamiento y comienza a ingresar a Orion.',
    descEn:
      'The crew arrives at the "White Room" on the launch tower and begins boarding Orion.',
    phase: "Prelaunch",
    attitude: "Pad 39B",
    isRoutine: false,
    days: 0,
    hours: -3,
    minutes: -15,
  },
  {
    title: "🚪 Cierre de Escotilla",
    titleEn: "🚪 Hatch Closure",
    desc: "Se cierra y sella la escotilla lateral de Orion. Pruebas de estanqueidad en curso.",
    descEn:
      "Orion's side hatch is closed and sealed. Leak checks are underway.",
    phase: "Prelaunch",
    attitude: "Pad 39B",
    isRoutine: false,
    days: 0,
    hours: -2,
    minutes: -10,
  },
  {
    title: "⏱️ Cuenta Regresiva Terminal",
    titleEn: "⏱️ Terminal Countdown",
    desc: 'El Director de Lanzamiento da el "GO" final. Inicia la cuenta regresiva automatizada.',
    descEn:
      'The Launch Director gives the final "GO". Automated countdown initiates.',
    phase: "Prelaunch",
    attitude: "Pad 39B",
    isRoutine: false,
    days: 0,
    hours: 0,
    minutes: -10,
  },
  {
    title: "💻 Traspaso a Ordenadores (Hand-off)",
    titleEn: "💻 Auto Sequence Hand-off",
    desc: "Los sistemas de tierra ceden el control a los ordenadores de vuelo del SLS. Inicia secuencia de ignición.",
    descEn:
      "Ground systems hand off control to SLS flight computers. Ignition sequence begins.",
    phase: "Prelaunch",
    attitude: "Pad 39B",
    isRoutine: false,
    days: 0,
    hours: 0,
    minutes: -1,
  },

  // ==========================================
  // --- DÍA 1 (FD01): ÓRBITA TERRESTRE BAJA (LEO) ---
  // ==========================================
  {
    title: "🚀 Despegue (Ascent)",
    titleEn: "🚀 Liftoff (Ascent)",
    desc: "Los motores RS-25 y propulsores sólidos cobran vida. Inicio oficial del reloj MET[cite: 105].",
    descEn:
      "RS-25 engines and solid boosters come to life. Official start of the MET clock[cite: 105].",
    phase: "Ascent",
    attitude: "Ascent",
    isRoutine: false,
    days: 0,
    hours: 0,
    minutes: 0,
  },
  {
    title: "🌬️ Despresurización (DFTO 3, 2)",
    titleEn: "🌬️ Cabin Depress (DFTO 3, 2)",
    desc: "Prueba de estanqueidad de los trajes espaciales. Se reduce la presión de la cabina intencionalmente[cite: 137].",
    descEn:
      "Spacesuit seal test. Cabin pressure is intentionally reduced[cite: 137].",
    phase: "Ascent",
    attitude: "Ascent",
    isRoutine: false,
    days: 0,
    hours: 0,
    minutes: 30,
  },
  {
    title: "🔥 Elevación de Perigeo (ICPS PRM)",
    titleEn: "🔥 Perigee Raise Maneuver (ICPS PRM)",
    desc: "La etapa superior enciende motores para estabilizar la órbita inicial a los 50 minutos del vuelo[cite: 131].",
    descEn:
      "The upper stage fires engines to stabilize initial orbit 50 minutes into flight[cite: 131].",
    phase: "LEO",
    attitude: "MNVRS",
    isRoutine: false,
    days: 0,
    hours: 0,
    minutes: 50,
  },
  {
    title: "💻 Pre ARB C/Os",
    titleEn: "💻 Pre ARB C/Os",
    desc: "Chequeos previos de los sistemas antes de la maniobra de elevación de apogeo[cite: 106].",
    descEn:
      "Preliminary systems checkouts prior to the apogee raise maneuver[cite: 106].",
    phase: "LEO",
    attitude: "MNVRs",
    isRoutine: false,
    days: 0,
    hours: 1,
    minutes: 0,
  },
  {
    title: "🔥 Elevación de Apogeo (ARB TIG)",
    titleEn: "🔥 Apogee Raise Burn (ARB TIG)",
    desc: "Encendido programado a las 0/01:47 para alargar la órbita de forma elíptica para ganar altura[cite: 136].",
    descEn:
      "Burn scheduled at 0/01:47 to elongate the orbit elliptically to gain altitude[cite: 136].",
    phase: "LEO",
    attitude: "ARB",
    isRoutine: false,
    days: 0,
    hours: 1,
    minutes: 47,
  },
  {
    title: "🧑‍🚀 Retirada de Trajes (Doff OCSS)",
    titleEn: "🧑‍🚀 Doff Survival Suits (OCSS)",
    desc: "Los astronautas se quitan los pesados trajes anaranjados de supervivencia Orion Crew Survival System[cite: 110].",
    descEn:
      "Astronauts take off the heavy orange Orion Crew Survival System suits[cite: 110].",
    phase: "LEO",
    attitude: "B-XSI",
    isRoutine: true,
    days: 0,
    hours: 2,
    minutes: 30,
  },
  {
    title: "🔗 Separación Orion/ICPS",
    titleEn: "🔗 Orion/ICPS Spring Sep",
    desc: "La nave Orion se desconecta físicamente de la etapa superior mediante resortes a las 3 horas y 23 minutos[cite: 132, 133].",
    descEn:
      "Orion spacecraft physically disconnects from the upper stage via springs at 3 hours 23 minutes[cite: 132, 133].",
    phase: "LEO",
    attitude: "B-XSI",
    isRoutine: false,
    days: 0,
    hours: 3,
    minutes: 23,
  },
  {
    title: "🛰️ Prox Ops Demo (Orion USS)",
    titleEn: "🛰️ Prox Ops Demo (Orion USS)",
    desc: "A las 0/04:51, los astronautas prueban el control manual volando en proximidad a la etapa descartada[cite: 111, 138].",
    descEn:
      "At 0/04:51, astronauts test manual controls flying in proximity to the discarded stage[cite: 111, 138].",
    phase: "LEO",
    attitude: "Prox Ops Demo",
    isRoutine: false,
    days: 0,
    hours: 4,
    minutes: 51,
  },
  {
    title: "🗑️ Encendido de Descarte (ICPS Disposal)",
    titleEn: "🗑️ ICPS Disposal Burn",
    desc: "La etapa ICPS enciende su motor a las 0/05:02 para alejarse hacia una órbita cementerio segura[cite: 138].",
    descEn:
      "The ICPS stage fires its engine at 0/05:02 to move to a safe graveyard orbit[cite: 138].",
    phase: "LEO",
    attitude: "Bias -XSI",
    isRoutine: false,
    days: 0,
    hours: 5,
    minutes: 2,
  },
  {
    title: "☀️ Despliegue de Paneles (SPL)",
    titleEn: "☀️ Solar Panel Deploy (SPL)",
    desc: "A las 0/05:27, el Módulo de Servicio Europeo despliega sus cuatro paneles solares[cite: 139].",
    descEn:
      "At 0/05:27, the European Service Module deploys its four solar arrays[cite: 139].",
    phase: "LEO",
    attitude: "Bias -XSI",
    isRoutine: false,
    days: 0,
    hours: 5,
    minutes: 27,
  },
  {
    title: "📷 Calibración de Cámara (Dock Cam Bearing)",
    titleEn: "📷 Dock Cam Bearing",
    desc: "Alineación de orientación (bearing) de la cámara óptica programada a las 0/06:00[cite: 139].",
    descEn: "Optical camera bearing alignment scheduled at 0/06:00[cite: 139].",
    phase: "LEO",
    attitude: "Bias -XSI",
    isRoutine: false,
    days: 0,
    hours: 6,
    minutes: 0,
  },
  {
    title: "🍲 Configuración de Cabina",
    titleEn: "🍲 Cabin Config",
    desc: "Organización de los suministros dentro de la cápsula[cite: 112].",
    descEn: "Organization of supplies inside the capsule[cite: 112].",
    phase: "LEO",
    attitude: "Bias -XSI",
    isRoutine: true,
    days: 0,
    hours: 6,
    minutes: 30,
  },
  {
    title: "🎙️ Chequeos PAD / PMC",
    titleEn: "🎙️ PAD / PMC Checks",
    desc: "Conferencia médica privada (PMC) y revisión de Datos de Asesoramiento Preliminar[cite: 114, 115].",
    descEn:
      "Private medical conference (PMC) and Preliminary Advisory Data review[cite: 114, 115].",
    phase: "LEO",
    attitude: "Bias -XSI",
    isRoutine: true,
    days: 0,
    hours: 7,
    minutes: 30,
  },
  {
    title: "💤 Primer Ciclo de Sueño (4 hrs)",
    titleEn: "💤 First Sleep Cycle (4 hrs)",
    desc: "Breve descanso de 4 horas para la tripulación tras la jornada de lanzamiento[cite: 116].",
    descEn: "Brief 4-hour crew rest after the launch day[cite: 116].",
    phase: "High Earth Orbit",
    attitude: "Bias -XSI",
    isRoutine: true,
    days: 0,
    hours: 8,
    minutes: 0,
  },
  {
    title: "📡 Activación OpComm",
    titleEn: "📡 OpComm Activation",
    desc: "Activación inicial del sistema de comunicaciones ópticas láser a las 0/10:06[cite: 134].",
    descEn:
      "Initial activation of the laser optical communications system at 0/10:06[cite: 134].",
    phase: "High Earth Orbit",
    attitude: "Bias -XSI",
    isRoutine: false,
    days: 0,
    hours: 10,
    minutes: 6,
  },
  {
    title: "🔥 Orion PRB",
    titleEn: "🔥 Orion Perigee Raise Burn (PRB)",
    desc: "Orion enciende su motor principal a las 0/13:30 para ajustar la órbita final antes de saltar a la Luna[cite: 135].",
    descEn:
      "Orion fires its main engine at 0/13:30 to adjust final orbit before jumping to the Moon[cite: 135].",
    phase: "High Earth Orbit",
    attitude: "Bias -XSI",
    isRoutine: false,
    days: 0,
    hours: 13,
    minutes: 30,
  },
  {
    title: "🔭 OpNav C/O",
    titleEn: "🔭 OpNav C/O",
    desc: "Chequeos del sistema de navegación óptica de la nave a las 0/14:15[cite: 140].",
    descEn: "Optical navigation system checkouts at 0/14:15[cite: 140].",
    phase: "High Earth Orbit",
    attitude: "Bias -XSI",
    isRoutine: false,
    days: 0,
    hours: 14,
    minutes: 15,
  },
  {
    title: "💤 Segundo Sueño (4.5 hrs)",
    titleEn: "💤 Second Sleep (4.5 hrs)",
    desc: "Ciclo de descanso principal de 4.5 horas para prepararse para la inyección lunar[cite: 119].",
    descEn:
      "Main 4.5-hour sleep cycle to prepare for lunar injection[cite: 119].",
    phase: "High Earth Orbit",
    attitude: "Bias -XSI",
    isRoutine: true,
    days: 0,
    hours: 15,
    minutes: 0,
  },
  {
    title: "💪 Prueba de Ejercicio",
    titleEn: "💪 Exercise Test",
    desc: "Prueba de los equipos de ejercicio resistivo de la cabina[cite: 146].",
    descEn: "Test of the cabin's resistive exercise equipment[cite: 146].",
    phase: "High Earth Orbit",
    attitude: "Bias -XSI",
    isRoutine: true,
    days: 0,
    hours: 22,
    minutes: 0,
  },
  {
    title: "🌬️ ECLSS CO2 Monitor DFTO",
    titleEn: "🌬️ ECLSS CO2 Monitor DFTO",
    desc: "Prueba de vuelo del monitor de dióxido de carbono del sistema de soporte vital[cite: 168].",
    descEn:
      "Flight test of the life support system's carbon dioxide monitor[cite: 168].",
    phase: "High Earth Orbit",
    attitude: "Bias -XSI",
    isRoutine: false,
    days: 0,
    hours: 23,
    minutes: 0,
  },
  {
    title: "🛠️ Desmontaje de Soportes",
    titleEn: "🛠️ Asc Bracket Uninstall",
    desc: "Desmontaje de la cámara de acoplamiento y soportes de ascenso para liberar espacio[cite: 171].",
    descEn:
      "Uninstalling the docking camera and ascent brackets to free up space[cite: 171].",
    phase: "High Earth Orbit",
    attitude: "Bias -XSI",
    isRoutine: false,
    days: 0,
    hours: 23,
    minutes: 30,
  },

  // ==========================================
  // --- DÍA 2 (FD02): HACIA LA LUNA ---
  // ==========================================
  {
    title: "🚀 Inyección Trans-Lunar (Orion TLI)",
    titleEn: "🚀 Trans-Lunar Injection (Orion TLI)",
    desc: "Encendido principal a las 01/01:08:42. La nave abandona la Tierra rumbo a la Luna[cite: 169].",
    descEn:
      "Main burn at 01/01:08:42. The ship leaves Earth heading for the Moon[cite: 169].",
    phase: "Trans-Lunar",
    attitude: "TLI",
    isRoutine: false,
    days: 1,
    hours: 1,
    minutes: 8,
  },
  {
    title: "🍲 Comida",
    titleEn: "🍲 Meal",
    desc: "Rutina de comida para la tripulación[cite: 176].",
    descEn: "Meal routine for the crew[cite: 176].",
    phase: "Trans-Lunar",
    attitude: "Bias -XSI",
    isRoutine: true,
    days: 1,
    hours: 2,
    minutes: 0,
  },
  {
    title: "🎙️ Evento PAO",
    titleEn: "🎙️ PAO Event",
    desc: "Conexión de la Oficina de Asuntos Públicos[cite: 179].",
    descEn: "Public Affairs Office connection[cite: 179].",
    phase: "Trans-Lunar",
    attitude: "Bias -XSI",
    isRoutine: true,
    days: 1,
    hours: 4,
    minutes: 0,
  },
  {
    title: "👀 Inspección de Ventanas",
    titleEn: "👀 Window Inspect",
    desc: "Inspección visual detallada de las ventanas de la cápsula[cite: 180].",
    descEn: "Detailed visual inspection of capsule windows[cite: 180].",
    phase: "Trans-Lunar",
    attitude: "Bias -XSI",
    isRoutine: false,
    days: 1,
    hours: 5,
    minutes: 0,
  },
  {
    title: "🛠️ Instalación de Soportes Duales",
    titleEn: "🛠️ Dual Cam Bracket Install",
    desc: "Instalación del soporte de cámara dual para operaciones en el espacio profundo[cite: 170].",
    descEn:
      "Installation of the dual camera bracket for deep space operations[cite: 170].",
    phase: "Trans-Lunar",
    attitude: "Bias -XSI",
    isRoutine: false,
    days: 1,
    hours: 6,
    minutes: 0,
  },
  {
    title: "💤 Sueño en Espacio Profundo (8.5 hrs)",
    titleEn: "💤 Deep Space Sleep (8.5 hrs)",
    desc: "Ciclo de descanso estándar de 8.5 horas[cite: 182].",
    descEn: "Standard 8.5-hour rest cycle[cite: 182].",
    phase: "Trans-Lunar",
    attitude: "Bias -XSI",
    isRoutine: true,
    days: 1,
    hours: 10,
    minutes: 0,
  },
  {
    title: "🔍 Inspección Térmica (CM/SM Survey)",
    titleEn: "🔍 Thermal Inspection (CM/SM Survey)",
    desc: "Uso de cámaras a las 01/14:00 para escanear el escudo térmico buscando daños[cite: 186].",
    descEn:
      "Use of cameras at 01/14:00 to scan the heat shield for damage[cite: 186].",
    phase: "Trans-Lunar",
    attitude: "Survey",
    isRoutine: false,
    days: 1,
    hours: 14,
    minutes: 0,
  },
  {
    title: "📡 Demo OpCom ANU",
    titleEn: "📡 OpCom ANU Demo",
    desc: "Demostración de enlace avanzado del sistema de comunicaciones ópticas[cite: 186].",
    descEn:
      "Advanced link demonstration of the optical communications system[cite: 186].",
    phase: "Trans-Lunar",
    attitude: "Bias -XSI",
    isRoutine: false,
    days: 1,
    hours: 15,
    minutes: 0,
  },

  // ==========================================
  // --- DÍA 3 (FD03): OPERACIONES EN TRÁNSITO ---
  // ==========================================
  {
    title: "🛠️ OTC-1",
    titleEn: "🛠️ OTC-1",
    desc: "Primera corrección de trayectoria de ida programada a las 02/01:08:42[cite: 249].",
    descEn:
      "First Outbound Trajectory Correction burn scheduled at 02/01:08:42[cite: 249].",
    phase: "Trans-Lunar",
    attitude: "OTC",
    isRoutine: false,
    days: 2,
    hours: 1,
    minutes: 8,
  },
  {
    title: "🩺 Demo de RCP",
    titleEn: "🩺 CPR Demo",
    desc: "Los astronautas realizan una demostración de Resucitación Cardiopulmonar (CPR) en microgravedad[cite: 229, 230].",
    descEn:
      "Astronauts perform a Cardiopulmonary Resuscitation (CPR) demo in microgravity[cite: 229, 230].",
    phase: "Trans-Lunar",
    attitude: "Bias -XSI",
    isRoutine: true,
    days: 2,
    hours: 3,
    minutes: 0,
  },
  {
    title: "📡 Prueba Modo SAT",
    titleEn: "📡 SAT Mode Test",
    desc: "Prueba del modo satélite de comunicaciones[cite: 232, 233].",
    descEn: "Test of the satellite communications mode[cite: 232, 233].",
    phase: "Trans-Lunar",
    attitude: "DFTO",
    isRoutine: false,
    days: 2,
    hours: 5,
    minutes: 0,
  },
  {
    title: "⚕️ Med Kit",
    titleEn: "⚕️ Med Kit",
    desc: "Revisión del kit médico de a bordo[cite: 234].",
    descEn: "Review of the onboard medical kit[cite: 234].",
    phase: "Trans-Lunar",
    attitude: "Bias -XSI",
    isRoutine: true,
    days: 2,
    hours: 6,
    minutes: 0,
  },
  {
    title: "🌙 Lunar Cab",
    titleEn: "🌙 Lunar Cab",
    desc: "Configuración de la cabina para operaciones de proximidad lunar[cite: 235, 236].",
    descEn:
      "Cabin configuration for lunar proximity operations[cite: 235, 236].",
    phase: "Trans-Lunar",
    attitude: "Bias -XSI",
    isRoutine: false,
    days: 2,
    hours: 7,
    minutes: 0,
  },
  {
    title: "📞 Enlace DSN de Emergencia",
    titleEn: "📞 DSN Emergency Comms",
    desc: "Prueba de enlace de emergencia (EMER Comm DFTO-EM2-22) con la Red del Espacio Profundo[cite: 250].",
    descEn:
      "Emergency link test (EMER Comm DFTO-EM2-22) with the Deep Space Network[cite: 250].",
    phase: "Trans-Lunar",
    attitude: "Bias -XSI",
    isRoutine: false,
    days: 2,
    hours: 8,
    minutes: 0,
  },
  {
    title: "🎙️ CSA PAO",
    titleEn: "🎙️ CSA PAO Event",
    desc: "Enlace exclusivo con la Agencia Espacial Canadiense (CSA)[cite: 237, 238].",
    descEn:
      "Exclusive link with the Canadian Space Agency (CSA)[cite: 237, 238].",
    phase: "Trans-Lunar",
    attitude: "Bias -XSI",
    isRoutine: true,
    days: 2,
    hours: 9,
    minutes: 0,
  },
  {
    title: "📷 Prueba Misalign Cámara",
    titleEn: "📷 Dock Cam Misalign Test",
    desc: "Prueba DFTO-EM2-03 forzando una desalineación virtual de la cámara óptica[cite: 251].",
    descEn:
      "Test DFTO-EM2-03 forcing a virtual misalignment of the optical camera[cite: 251].",
    phase: "Trans-Lunar",
    attitude: "FTO",
    isRoutine: false,
    days: 2,
    hours: 10,
    minutes: 0,
  },
  {
    title: "💤 Ciclo de Sueño (FD03)",
    titleEn: "💤 Sleep Cycle (FD03)",
    desc: "Descanso de 8.5 horas[cite: 241].",
    descEn: "8.5 hours rest[cite: 241].",
    phase: "Trans-Lunar",
    attitude: "Bias -XSI",
    isRoutine: true,
    days: 2,
    hours: 12,
    minutes: 0,
  },

  // ==========================================
  // --- DÍA 4 (FD04): AJUSTES FINOS ---
  // ==========================================
  {
    title: "🛠️ OTC-2",
    titleEn: "🛠️ OTC-2",
    desc: "Segunda corrección de trayectoria programada a las 3/01:08:42[cite: 334].",
    descEn: "Second trajectory correction scheduled at 3/01:08:42[cite: 334].",
    phase: "Trans-Lunar",
    attitude: "OTC",
    isRoutine: false,
    days: 3,
    hours: 1,
    minutes: 8,
  },
  {
    title: "🥵 Min ECLSS DFTO",
    titleEn: "🥵 Min ECLSS DFTO",
    desc: "Prueba técnica EM2-18 para los sistemas ambientales vitales mínimos[cite: 335].",
    descEn:
      "Technical test EM2-18 for minimum vital environmental systems[cite: 335].",
    phase: "Trans-Lunar",
    attitude: "Bias -XSI",
    isRoutine: false,
    days: 3,
    hours: 2,
    minutes: 0,
  },
  {
    title: "🎧 Inicio DFTO Acústico (24h)",
    titleEn: "🎧 Start 24h Acoustic DFTO",
    desc: "Comienza una prueba de medición continua de ruido ambiental (EM2-7)[cite: 336].",
    descEn:
      "Starts a continuous ambient noise measurement test (EM2-7)[cite: 336].",
    phase: "Trans-Lunar",
    attitude: "Bias -XSI",
    isRoutine: false,
    days: 3,
    hours: 3,
    minutes: 0,
  },
  {
    title: "📷 Instalación de Soportes de Cámara",
    titleEn: "📷 Dock Cam & Bracket Install",
    desc: "Instalación de herramientas ópticas adicionales[cite: 337].",
    descEn: "Installation of additional optical tools[cite: 337].",
    phase: "Trans-Lunar",
    attitude: "Bias -XSI",
    isRoutine: false,
    days: 3,
    hours: 4,
    minutes: 0,
  },
  {
    title: "🧭 Prueba de Navegación",
    titleEn: "🧭 NAV FTO",
    desc: "Prueba de objetivos de vuelo de navegación a las 03/07:00 (EM2-223)[cite: 338].",
    descEn:
      "Navigation flight objectives test at 03/07:00 (EM2-223)[cite: 338].",
    phase: "Trans-Lunar",
    attitude: "DFTO",
    isRoutine: false,
    days: 3,
    hours: 7,
    minutes: 0,
  },
  {
    title: "💤 Ciclo de Sueño Adelantado",
    titleEn: "💤 Early Sleep Cycle",
    desc: "Descanso de 8.5 horas desplazado 45 minutos antes para prepararse para la Luna[cite: 316].",
    descEn:
      "8.5-hour rest shifted 45 minutes earlier in preparation for the Moon[cite: 316].",
    phase: "Trans-Lunar",
    attitude: "Bias -XSI",
    isRoutine: true,
    days: 3,
    hours: 10,
    minutes: 0,
  },

  // ==========================================
  // --- DÍA 5 (FD05): EL ENCUENTRO LUNAR ---
  // ==========================================
  {
    title: "🛠️ OTC-3",
    titleEn: "🛠️ OTC-3",
    desc: "Tercera y última corrección propulsada (4/04:29:52) antes de la influencia lunar[cite: 380].",
    descEn:
      "Third and final powered correction (4/04:29:52) before lunar influence[cite: 380].",
    phase: "Trans-Lunar",
    attitude: "OTC",
    isRoutine: false,
    days: 4,
    hours: 4,
    minutes: 29,
  },
  {
    title: "🌑 Entrada Esfera Lunar (SOI Entry)",
    titleEn: "🌑 Lunar SOI Entry",
    desc: "Orion cruza la frontera gravitacional de la Luna a las 4/06:38[cite: 380].",
    descEn:
      "Orion crosses the Moon's gravitational boundary at 4/06:38[cite: 380].",
    phase: "Trans-Lunar",
    attitude: "Bias -XSI",
    isRoutine: false,
    days: 4,
    hours: 6,
    minutes: 38,
  },
  {
    title: "🎧 Fin DFTO Acústico",
    titleEn: "🎧 End 24h Acoustic DFTO",
    desc: "Finaliza la grabación ambiental de 24 horas[cite: 371].",
    descEn: "24-hour ambient recording ends[cite: 371].",
    phase: "Trans-Lunar",
    attitude: "Bias -XSI",
    isRoutine: false,
    days: 4,
    hours: 7,
    minutes: 0,
  },
  {
    title: "🌬️ Venteo a 10.2 psi",
    titleEn: "🌬️ Vent to 10.2 psi",
    desc: "Se iguala la presión de la cabina a niveles reducidos[cite: 372].",
    descEn: "Cabin pressure is equalized to reduced levels[cite: 372].",
    phase: "Trans-Lunar",
    attitude: "Bias -XSI",
    isRoutine: false,
    days: 4,
    hours: 9,
    minutes: 0,
  },
  {
    title: "📷 Prueba Misalign Cámara",
    titleEn: "📷 Dock Cam Misalign Test",
    desc: "Prueba DFTO-EM2-03 antes de acercarse a la superficie lunar[cite: 373].",
    descEn:
      "Test DFTO-EM2-03 prior to approaching the lunar surface[cite: 373].",
    phase: "Trans-Lunar",
    attitude: "Bias -XSI",
    isRoutine: false,
    days: 4,
    hours: 10,
    minutes: 0,
  },
  {
    title: "💤 Ciclo de Sueño (Prevuelo Lunar)",
    titleEn: "💤 Sleep Cycle (Pre-flyby)",
    desc: "Descanso desplazado 1 hora antes; el último antes del encuentro[cite: 379].",
    descEn:
      "Rest shifted 1 hour earlier; the last before the encounter[cite: 379].",
    phase: "Trans-Lunar",
    attitude: "Bias -XSI",
    isRoutine: true,
    days: 4,
    hours: 12,
    minutes: 0,
  },

  // ==========================================
  // --- DÍA 6 (FD06): SOBREVUELO LUNAR ---
  // ==========================================
  {
    title: "🌕 Máximo Acercamiento Lunar",
    titleEn: "🌕 Lunar Close Approach",
    desc: "Punto más cercano en la cara oculta de la Luna a las 5/00:29:59[cite: 434].",
    descEn:
      "Closest point on the far side of the Moon at 5/00:29:59[cite: 434].",
    phase: "Trans-Earth",
    attitude: "Nav",
    isRoutine: false,
    days: 5,
    hours: 0,
    minutes: 29,
  },
  {
    title: "🌌 Máxima Distancia Terrestre",
    titleEn: "🌌 Max Earth Distance",
    desc: "El punto más alejado de la Tierra a las 5/00:35[cite: 434].",
    descEn: "The furthest point from Earth at 5/00:35[cite: 434].",
    phase: "Trans-Earth",
    attitude: "Nav",
    isRoutine: false,
    days: 5,
    hours: 0,
    minutes: 35,
  },
  {
    title: "🏆 Récord Apollo",
    titleEn: "🏆 Apollo Record",
    desc: "La tripulación rompe el récord de distancia histórica[cite: 433].",
    descEn: "The crew breaks the historical distance record[cite: 433].",
    phase: "Trans-Earth",
    attitude: "Bias -XSI",
    isRoutine: false,
    days: 5,
    hours: 2,
    minutes: 0,
  },
  {
    title: "🔭 Observaciones Lunares",
    titleEn: "🔭 Lunar Obs",
    desc: "Observaciones visuales de la superficie de la Luna tras el sobrevuelo[cite: 418].",
    descEn:
      "Visual observations of the Moon's surface following the flyby[cite: 418].",
    phase: "Trans-Earth",
    attitude: "Obsv",
    isRoutine: true,
    days: 5,
    hours: 4,
    minutes: 0,
  },
  {
    title: "🔍 Inspección Post-Lunar (CM/SM Survey)",
    titleEn: "🔍 Post-Lunar Survey",
    desc: "Revisión externa del escudo térmico a las 05/12:30[cite: 435].",
    descEn: "External review of the heat shield at 05/12:30[cite: 435].",
    phase: "Trans-Earth",
    attitude: "Survey",
    isRoutine: false,
    days: 5,
    hours: 12,
    minutes: 30,
  },
  {
    title: "🌍 Salida Esfera Lunar (SOI Exit)",
    titleEn: "🌍 Lunar SOI Exit",
    desc: "Salida de la influencia gravitacional de la Luna a las 5/18:53[cite: 436].",
    descEn:
      "Exit from the Moon's gravitational influence at 5/18:53[cite: 436].",
    phase: "Trans-Earth",
    attitude: "Bias -XSI",
    isRoutine: false,
    days: 5,
    hours: 18,
    minutes: 53,
  },
  {
    title: "💤 Sueño Profundo (9.5 hrs)",
    titleEn: "💤 Deep Sleep (9.5 hrs)",
    desc: "Turno extendido de sueño de 9.5 horas desplazado 1 hora más tarde[cite: 420].",
    descEn: "Extended 9.5-hour sleep shift pushed 1 hour later[cite: 420].",
    phase: "Trans-Earth",
    attitude: "Bias -XSI",
    isRoutine: true,
    days: 5,
    hours: 20,
    minutes: 0,
  },

  // ==========================================
  // --- DÍA 7 (FD07) - DÍA 8 (FD08): EL REGRESO ---
  // ==========================================
  {
    title: "🛠️ RTC-1",
    titleEn: "🛠️ RTC-1",
    desc: "Primera corrección de trayectoria de retorno programada a las 6/01:29:52[cite: 438].",
    descEn:
      "First Return Trajectory Correction burn scheduled at 6/01:29:52[cite: 438].",
    phase: "Trans-Earth",
    attitude: "RTC1",
    isRoutine: false,
    days: 6,
    hours: 1,
    minutes: 29,
  },
  {
    title: "📷 Descarga de Datos de Cámara",
    titleEn: "📷 Dock Cam WW Dump",
    desc: "Descarga de datos capturados por los objetivos de vuelo (Dock Cam WW Dump FTO)[cite: 440].",
    descEn:
      "Download of data captured by flight objectives (Dock Cam WW Dump FTO)[cite: 440].",
    phase: "Trans-Earth",
    attitude: "Bias -XSI",
    isRoutine: false,
    days: 6,
    hours: 5,
    minutes: 0,
  },
  {
    title: "📷 Prueba Misalign Cámara",
    titleEn: "📷 Dock Cam Misalign",
    desc: "Continuación de las pruebas de desalineación en el trayecto de vuelta[cite: 441].",
    descEn:
      "Continuation of misalignment tests on the return journey[cite: 441].",
    phase: "Trans-Earth",
    attitude: "Bias -XSI",
    isRoutine: false,
    days: 6,
    hours: 6,
    minutes: 0,
  },
  {
    title: "☢️ Refugio de Radiación Demo",
    titleEn: "☢️ Rad Shelter Demo",
    desc: "Prueba de construcción del refugio contra tormentas solares utilizando el almacenamiento interno[cite: 447].",
    descEn:
      "Test construction of the solar storm radiation shelter using internal storage[cite: 447].",
    phase: "Trans-Earth",
    attitude: "DFTO",
    isRoutine: false,
    days: 7,
    hours: 4,
    minutes: 0,
  },
  {
    title: "💻 FCS Checkouts",
    titleEn: "💻 FCS Checkouts",
    desc: "Pruebas de los ordenadores del Sistema de Control de Vuelo (FCS) a las 7/17:30[cite: 504].",
    descEn:
      "Tests of the Flight Control System (FCS) computers at 7/17:30[cite: 504].",
    phase: "Trans-Earth",
    attitude: "Bias -XSI",
    isRoutine: false,
    days: 7,
    hours: 17,
    minutes: 30,
  },
  {
    title: "📊 Modal Survey DFTO",
    titleEn: "📊 Modal Survey DFTO",
    desc: "Inspecciones de la dinámica y vibraciones estructurales del módulo de la tripulación (EM2-27)[cite: 456].",
    descEn:
      "Inspections of structural dynamics and vibrations of the crew module (EM2-27)[cite: 456].",
    phase: "Trans-Earth",
    attitude: "Bias -XSI",
    isRoutine: false,
    days: 7,
    hours: 19,
    minutes: 0,
  },
  {
    title: "💧 Venteo de Orina al Vacío",
    titleEn: "💧 Urine Venting Test",
    desc: "Prueba de expulsión al espacio profundo (DFTO EM2-26)[cite: 459].",
    descEn: "Expulsion test into deep space (DFTO EM2-26)[cite: 459].",
    phase: "Trans-Earth",
    attitude: "Bias -XSI",
    isRoutine: false,
    days: 7,
    hours: 21,
    minutes: 0,
  },

  // ==========================================
  // --- DÍA 9 (FD09/10): REENTRADA Y AMERIZAJE ---
  // ==========================================
  {
    title: "🌬️ Represurización a 14.7 psi",
    titleEn: "🌬️ Repress to 14.7 psi",
    desc: "Restauración de la presión de la cabina a niveles estándar[cite: 461].",
    descEn: "Restoration of cabin pressure to standard levels[cite: 461].",
    phase: "Trans-Earth",
    attitude: "Bias -XSI",
    isRoutine: false,
    days: 8,
    hours: 1,
    minutes: 0,
  },
  {
    title: "🧑‍🚀 Colocación Trajes (OIG Don)",
    titleEn: "🧑‍🚀 Suit Up (OIG Don)",
    desc: "Los astronautas se ponen los trajes naranjas de supervivencia preparando el aterrizaje[cite: 469].",
    descEn:
      "Astronauts don orange survival suits preparing for landing[cite: 469].",
    phase: "Trans-Earth",
    attitude: "DFTO",
    isRoutine: true,
    days: 8,
    hours: 3,
    minutes: 0,
  },
  {
    title: "🛠️ RTC-2",
    titleEn: "🛠️ RTC-2",
    desc: "Ajuste fino programado a las 8/04:29:10 para asegurar el pasillo atmosférico[cite: 505].",
    descEn:
      "Fine tuning scheduled at 8/04:29:10 to secure the atmospheric corridor[cite: 505].",
    phase: "Trans-Earth",
    attitude: "RTC",
    isRoutine: false,
    days: 8,
    hours: 4,
    minutes: 29,
  },
  {
    title: "🎒 Aseguramiento de Carga (Entry Stow)",
    titleEn: "🎒 Entry Stow",
    desc: "Guardado final de todos los objetos sueltos de la cabina[cite: 494].",
    descEn: "Final stowage of all loose cabin items[cite: 494].",
    phase: "Trans-Earth",
    attitude: "Entry Stow",
    isRoutine: true,
    days: 8,
    hours: 13,
    minutes: 0,
  },
  {
    title: "🛠️ RTC-3",
    titleEn: "🛠️ RTC-3",
    desc: "Último ajuste balístico directo hacia el Océano Pacífico a las 8/20:29:10[cite: 506].",
    descEn:
      "Final ballistic adjustment straight towards the Pacific Ocean at 8/20:29:10[cite: 506].",
    phase: "Trans-Earth",
    attitude: "RTC3",
    isRoutine: false,
    days: 8,
    hours: 20,
    minutes: 29,
  },
  {
    title: "🔗 Separación de Módulos (CM/SM Sep)",
    titleEn: "🔗 Module Separation (CM/SM Sep)",
    desc: "El Módulo de Servicio Europeo se descarta a las 09/01:09 para desintegrarse en la atmósfera[cite: 507].",
    descEn:
      "The European Service Module is discarded at 09/01:09 to burn up in the atmosphere[cite: 507].",
    phase: "EDL",
    attitude: "Entry C/L",
    isRoutine: false,
    days: 9,
    hours: 1,
    minutes: 9,
  },
  {
    title: "💧 Detección de Fugas +X",
    titleEn: "💧 +X Leak Detection",
    desc: "Prueba final de detección de fugas (DFTO) previa a la entrada atmosférica[cite: 508].",
    descEn:
      "Final leak detection test (DFTO) prior to atmospheric entry[cite: 508].",
    phase: "EDL",
    attitude: "Entry C/L",
    isRoutine: false,
    days: 9,
    hours: 1,
    minutes: 15,
  },
  {
    title: "🔥 Interfaz de Entrada (Reentrada)",
    titleEn: "🔥 Entry Interface",
    desc: "La cápsula golpea la atmósfera a Mach 32 a las 09/01:29[cite: 509].",
    descEn: "Capsule hits the atmosphere at Mach 32 at 09/01:29[cite: 509].",
    phase: "EDL",
    attitude: "Entry C/L",
    isRoutine: false,
    days: 9,
    hours: 1,
    minutes: 29,
  },
  {
    title: "🌊 Amerizaje (Splashdown)",
    titleEn: "🌊 Splashdown",
    desc: "Amerizaje en las aguas del Océano Pacífico a las 09/01:42:48. ¡Misión cumplida! [cite: 510]",
    descEn:
      "Splashdown in the waters of the Pacific Ocean at 09/01:42:48. Mission accomplished! [cite: 510]",
    phase: "Recovery",
    attitude: "Recovery Ops",
    isRoutine: false,
    days: 9,
    hours: 1,
    minutes: 42,
  },
];
